apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: learnhub
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /ecommerce(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ecommerce-service
                port:
                  number: 80
